### ISSUE TITLE
ability to translate Button text

### ISSUE THREAD

**Issue by andekande** [MessiJS/MessiJS#64]
messi.alert and messi.ask have default buttons with text OK, Yes, No
would me nice to be able to treanslate that, maybe with additional info in options.

**Comment by kgust** [comment]
Because MessiJS doesn't have a templating engine—adding translations would add a huge layer of complexity that I don't want to add right now—I've decided against adding this feature at this time.

Give me some good examples of how to do this without adding a lot of complexity and I'd reconsider.
