### ISSUE TITLE
Custom click function for Button

### ISSUE THREAD

**Issue by langigo** [MessiJS/MessiJS#65]
Is there any way I can implement my function to handle click event for a button.
For example I write a form as the message and I want the button can do something like submit that form by using jQuery. Messi has the callback but it only invoke after the dialog closed and the form was also destroyed.

**Comment by kgust** [comment]
You should be doing this (note the `unload: false`):

```javascript
var dialog = new Messi(
    "This is a message with Messi in modal view. Now you can't interact with other elements on the page until close this dialog.",
    {title: 'Modal Window', modal: true, unload: false}
);
```

At this point if you want the dialog to actually be removed, you'll have to remove it yourself.

_There is a bug in 2.0.1 where the modal overlay does not go away when using `unload: false`. This will be fixed in 2.0.2._
