### ISSUE TITLE
How do I press ESCAPE to close the modal?

### ISSUE THREAD

**Issue by andynhoo** [MessiJS/MessiJS#67]
How do I press ESCAPE to close the modal?
Would to close the modal call a function?

**Comment by kgust** [comment]
MessiJS currently does not support that feature. I've added this a feature request.

To answer your question—because this is not a supported feature—you would need to open the dialog, add a listener for either `onkeyup` or `onkeypress` and close the dialog if "ESC" is detected.

**Comment by kgust** [comment]
I'm closing this a duplicate of #18.
