### ISSUE TITLE
center: true on Chrome

### ISSUE THREAD

**Issue by entrican** [MessiJS/MessiJS#69]
It would seem that in my particular case, the $(window).height() property is being set improperly in chrome which caused the 'center: true' property to display a modal dialog outside the viewing area.

This seems to work just fine in IE and Chrome, but I didn't test any other browsers.

center: function () {
            this.messi.css({
                //top: ((jQuery(window).height() - this.messi.height()) / 2),
                //left: ((jQuery(window).width() - this.messi.width()) / 2)
                top: ((screen.height - this.messi.height()) / 2),
                left:((screen.width - this.messi.width()) / 2)
            });

I wanted to share my finding, but I don't have time for a formal contribution - i'm not up to speed on github participation.

-Robert
robert@entrican.com

**Comment by kgust** [comment]
I don't consider using `screen` for width and height to be valid. I am attempting to center the dialog in the viewport. `screen` gives the dimensions of the full computer's screen, which isn't helpful.
