### ISSUE TITLE
Bower package does not contain JS/CSS files

### ISSUE THREAD

**Issue by spectral-software** [MessiJS/MessiJS#72]
When installing MessiJS via bower, the package does not contain any JS or CSS files, only:
- images/
- .bower.json
- bower.json
- CONTRIBUTING.md
- LICENSE.md
- README.md

**Comment by kgust** [comment]
Make sure you are referencing the `MessiJS` bower package, not `messi`. I checked it; the `dist/` folder has the files you're looking for.
